### ISSUE TITLE
[Note] Transition implementation

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo-theme-proposal#1]
Note that transition can also be implemented using CSS variables:

```scss
body:not([data-theme-mount="true"]) .transition {
	transition-property: color, fill /* <svg> */, background-color, border-color, box-shadow;
	transition-duration: var(--transition-duration);
	transition-timing-function: var(--transition-timing-function);
}
body:not([data-theme-mount="true"]) .duration-75 {
	--transition-duration: 75ms;
}
body:not([data-theme-mount="true"]) .ease-out {
	--transition-timing-function: ease-out;
}
```

Whereas Tailwind implements transitions roughly like this:

```scss
.transition {
	transition-property: color, fill /* <svg> */, background-color, border-color, box-shadow;
}
.duration-75 {
	transition-duration: 75ms;
}
.ease-out {
	transition-timing-function: tokens.$ease-out;
}
```

Using the composition API seems easier to understand.
